apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: camunda-deployment
  namespace: camunda
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: camunda-deployment
    spec:
      containers:
      - name: camunda-tomcat
        image: docker.consulting.camunda.com/ee-tomcat:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regsecret          